on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: f4131189dfb7da2030c3536152c426a5e93cfae2
          SONAR_HOST_URL: http://localhost:9000
#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
